### ISSUE TITLE
Undocumented parameter in Engine::Callbacks

### ISSUE THREAD

**Issue by petersteneteg** [sgct/sgct#10]
What does the second param mean? 

https://github.com/sgct/sgct/blob/bc42ec6ffe7d67edda044eca5d4f23348fa5b5b1/include/sgct/engine.h#L100

**Comment by alexanderbock** [comment]
It's the position at which to start the decoding.  At the moment it's always going to be 0
https://github.com/sgct/sgct/blob/master/src/sgct/shareddata.cpp#L78
but I see that changing in the future and I would like to keep the interface stable for that change.

The way I'm using it in the examples:
https://github.com/sgct/sgct/blob/master/src/apps/calibrator/main.cpp#L504

**Comment by petersteneteg** [comment]
Ok
would probably make more sense to use a span as argument in the future
