### ISSUE TITLE
EquirectangularProjection producing planarprojection

### ISSUE THREAD

**Issue by micahnyc** [sgct/sgct#13]
using the attached config, an EquirectangularProjection was expected but a planarprojection was produced.

`<?xml version="1.0" ?>
<Cluster masterAddress="localhost" externalControlPort="20500">
    <Settings>
        <Display swapInterval="1" />
    </Settings>
    <Node address="localhost" port="20401">
        <Window fullScreen="false" name="OpenSpace">
            <Stereo type="none" />
            <Size x="1280" y="720" />
            <Pos x="50" y="50" />
            <Viewport tracked="true">
                <Pos x="0.0" y="0.0" />
                <Size x="1.0" y="1.0" />
                <EquirectangularProjection quality="high">
                </EquirectangularProjection>
            </Viewport>
        </Window>
    </Node>
    <User eyeSeparation="0.065">
        <Pos x="0.0" y="0.0" z="0.0" />
    </User>
</Cluster>
`

**Comment by alexanderbock** [comment]
![image](https://user-images.githubusercontent.com/4921724/98974901-b79d1c80-2515-11eb-98ed-7da5663ded75.png)


has been fixed since
