### ISSUE TITLE
crash when using "1.5k" or 1536 as option for fisheye quality

### ISSUE THREAD

**Issue by micahnyc** [sgct/sgct#42]
As outlined in docs and here in code: https://github.com/sgct/sgct/blob/3f9a8b76addfd97374c7eff26215f097bbd452e5/src/sgct/readconfig.cpp#L160 it should work but crashes in OpenSpace 0.16.0

**Comment by alexanderbock** [comment]
It crashes in 0.16.0 since that commit doesn't have the change in it.

Support was introduced in 3f9a8b76addfd97374c7eff26215f097bbd452e5  (2021-01-19) ;  0.16.0 was released (2020-12-09)
