### ISSUE TITLE
2nd viewport not working in two viewport config

### ISSUE THREAD

**Issue by micahnyc** [sgct/sgct#65]
(likely in all multi vp configs)

`{
  "version": 1,
  "masteraddress": "localhost",
  "externalcontrolport": 20500,
  "settings": {
    "display": {
      "swapinterval": 0
    }
  },
  "nodes": [
    {
      "address": "localhost",
      "port": 20401,
      "windows": [
        {
          "name": "OpenSpace",
          "fullscreen": false,
          "stereo": "none",
          "pos": { "x": 50, "y": 50 },
          "size": { "x": 1280, "y": 720 },
          "viewports": [
            {
              "tracked": true,
              "pos": { "x": 0.0, "y": 0.0 },
              "size": { "x": 0.5, "y": 1.0 },
              "projection": {
                "type": "PlanarProjection",
                "fov": {
                  "hfov": 80.0,
                  "vfov": 50.534015846724
                },
                "orientation": { "yaw": 0.0, "pitch": 0.0, "roll": 0.0 }
              }
            },
            {
              "tracked": true,
              "pos": { "x": 0.5, "y": 0.0 },
              "size": { "x": 0.5, "y": 1.0 },
              "projection": {
                "type": "PlanarProjection",
                "fov": {
                  "hfov": 80.0,
                  "vfov": 50.534015846724
                },
                "orientation": { "yaw": 45.0, "pitch": 0.0, "roll": 0.0 }
              }
            }
          ]
        }
      ]
    }
  ],
  "users": [
    {
      "eyeseparation": 0.065,
      "pos": { "x": 0.0, "y": 0.0, "z": 0.0 }
    }
  ]
}
`

**Comment by micahnyc** [comment]
![image](https://user-images.githubusercontent.com/708535/193949996-ef25c57e-baa3-4d8c-b3e4-2aabf1c36d38.png)

**Comment by alexanderbock** [comment]
Closed cc42a0c7443a7ca431c0ae558d547b6be93ad453
