### ISSUE TITLE
Mac arm build issues

### ISSUE THREAD

**Issue by possan** [sgct/sgct#82]
Hi, i'm doing some work for the Stockholm dome and i was trying to build the examples for my M-based mac.

I got it working after fiddling with cmake and replacing the bundled png library with a submodule:

PR to remove hardcoded mac arch string in cmake config: https://github.com/sgct/sgct/pull/81

Branch to switch out lpng for submoduled libpng https://github.com/possan/sgct/tree/png (I haven't tested this build on windows, it would be great if someone could do that.)

**Comment by alexanderbock** [comment]
Closed in 517e819a3ba2259251b5ea6174c3f77c5bd967be
