### ISSUE TITLE
Changes to MPCDI File Format are Needed due to E&S Changes

### ISSUE THREAD

**Issue by GPayne** [sgct/sgct#83]
The orignal MPCDI file format contained one .xml file for configuration, and one .pfm file for warp mesh. Both were contained in a single .mpcdi file (which is actually a zip compressed file), and each node in a cluster had its own corresponding file.

This was changed by E&S to now have a single .mpcdi file used by all nodes, which contains one .xml file and a .pfm file for each node.

SGCT support for this format will need to change to parse the single contained .xml file and find the entry that matches the node's name, and use that to:
1. get the corresponding planar projection FOV details
2. get the corresponding pfm warp grid data

Description of the new MPCDI XML, and steps required to match names and extract the corresponding FOV and warp:
The MPCDI file contains a <display> element, and a <files> element.
`<display>`
Within this element there exists a `buffer` element for each node in the cluster, which in turn contains a `region` element with all of the FOV and resolution information. The `buffer` id name matches to the name key/value pair in the sgct json configuration file for the corresponding node.
`<files>`
Within this element there exists a `fileset` element for each node in the cluster with the name of the warp mesh file to use. The region name matches to the `region` element `id` name in the corresponding buffer region in the `display` element above.

**Comment by alexanderbock** [comment]
Closed in df44a6fea8a1b02989ab16b1e2da775b7c54e956
