### ISSUE TITLE
Add option to flip/mirror the rendering in any viewport

### ISSUE THREAD

**Issue by WeirdRubberDuck** [sgct/sgct#95]
At IPS 2024, we came across a user with a special setup that would require mirroring/flipping a fisheye image along the X-axis (I think, but we should be able to do it both vertically and horizontally) and we found that there is currently no way to do this through the available config settings. 

We should add a setting to flip/mirror the rendered image of any viewport, along the x and/or y direction

**Comment by alexanderbock** [comment]
Closed in 7b08cda0ed002bda77f82a96ad721f34e7caa0a0

**Comment by WeirdRubberDuck** [comment]
Don't forget to update the documentation! @alexanderbock
