### ISSUE TITLE
Blacklevelmask seems to be inverted

### ISSUE THREAD

**Issue by micahnyc** [sgct/sgct#99]
Not sure exactly what is wrong but I was trying to use the "blacklevelmask" property for our viewports, however it didnt work how I was expecting. Can anyone try this and tell me if I am not understanding it right, or if its not working as expected? I even made an inverted one to try, which almost worked but the masked area was all white instead of all black...

[1024.json](https://github.com/user-attachments/files/17463030/1024.json)
![mask_01](https://github.com/user-attachments/assets/8563383d-07d3-4b03-986d-ce4e149f0ed9)
![mask_01_invert](https://github.com/user-attachments/assets/ea54b298-b3cf-4adb-8b74-6d497dbd306f)

**Comment by alexanderbock** [comment]
![image](https://github.com/user-attachments/assets/11b19ad0-77f1-489f-85d8-e590d213eb38)
![image (1)](https://github.com/user-attachments/assets/08af6c89-8eef-44f5-84f7-28aa909736fe)

**Comment by alexanderbock** [comment]
Should be checked with the `blendmask` option as well and then only have one of the two moving forward

**Comment by Arohdin** [comment]
Seems to work fine if you just remove the second `vp->renderMaskMesh` (and glBlendFunc call) part.

![image](https://github.com/user-attachments/assets/a12638f1-18f0-4245-8069-c4b46c661caf)

![image](https://github.com/user-attachments/assets/278d1d7c-9765-4949-8bcf-286c49adba66)

![image](https://github.com/user-attachments/assets/b58479cf-7471-4896-a560-e1d6ed88d4c5)
